* Import

In [1]:
import seaborn as sns
from sklearn.linear_model import LinearRegression
import pandas as pd
import numpy as np
from sklearn import metrics
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix,classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

* Read

In [2]:
data  = pd.read_csv("./mushrooms.csv.csv")
data

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0        p         x           s         n       t    p               f   
1        e         x           s         y       t    a               f   
2        e         b           s         w       t    l               f   
3        p         x           y         w       t    p               f   
4        e         x           s         g       f    n               f   
...    ...       ...         ...       ...     ...  ...             ...   
8119     e         k           s         n       f    n               a   
8120     e         x           s         n       f    n               a   
8121     e         f           s         n       f    n               a   
8122     p         k           y         n       f    y               f   
8123     e         x           s         n       f    n               a   

     gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
0               c         n          k  ...                        s   
1               c         b          k  ...                        s   
2               c         b          n  ...                        s   
3               c         n          n  ...                        s   
4               w         b          k  ...                        s   
...           ...       ...        ...  ...                      ...   
8119            c         b          y  ...                        s   
8120            c         b          y  ...                        s   
8121            c         b          n  ...                        s   
8122            c         n          b  ...                        k   
8123            c         b          y  ...                        s   

     stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                         w                      w         p          w   
1                         w                      w         p          w   
2                         w                      w         p          w   
3                         w                      w         p          w   
4                         w                      w         p          w   
...                     ...                    ...       ...        ...   
8119                      o                      o         p          o   
8120                      o                      o         p          n   
8121                      o                      o         p          o   
8122                      w                      w         p          w   
8123                      o                      o         p          o   

     ring-number ring-type spore-print-color population habitat  
0              o         p                 k          s       u  
1              o         p                 n          n       g  
2              o         p                 n          n       m  
3              o         p                 k          s       u  
4              o         e                 n          a       g  
...          ...       ...               ...        ...     ...  
8119           o         p                 b          c       l  
8120           o         p                 b          v       l  
8121           o         p                 b          c       l  
8122           o         e                 w          v       l  
8123           o         p                 o          c       l  

[8124 rows x 23 columns]

* See Structure

In [3]:
data.head(5)

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0     p         x           s         n       t    p               f   
1     e         x           s         y       t    a               f   
2     e         b           s         w       t    l               f   
3     p         x           y         w       t    p               f   
4     e         x           s         g       f    n               f   

  gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
0            c         n          k  ...                        s   
1            c         b          k  ...                        s   
2            c         b          n  ...                        s   
3            c         n          n  ...                        s   
4            w         b          k  ...                        s   

  stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   

  ring-number ring-type spore-print-color population habitat  
0           o         p                 k          s       u  
1           o         p                 n          n       g  
2           o         p                 n          n       m  
3           o         p                 k          s       u  
4           o         e                 n          a       g  

[5 rows x 23 columns]

In [4]:
data.tail(5)

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
8119     e         k           s         n       f    n               a   
8120     e         x           s         n       f    n               a   
8121     e         f           s         n       f    n               a   
8122     p         k           y         n       f    y               f   
8123     e         x           s         n       f    n               a   

     gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
8119            c         b          y  ...                        s   
8120            c         b          y  ...                        s   
8121            c         b          n  ...                        s   
8122            c         n          b  ...                        k   
8123            c         b          y  ...                        s   

     stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
8119                      o                      o         p          o   
8120                      o                      o         p          n   
8121                      o                      o         p          o   
8122                      w                      w         p          w   
8123                      o                      o         p          o   

     ring-number ring-type spore-print-color population habitat  
8119           o         p                 b          c       l  
8120           o         p                 b          v       l  
8121           o         p                 b          c       l  
8122           o         e                 w          v       l  
8123           o         p                 o          c       l  

[5 rows x 23 columns]

* See Information about data set

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8124 entries, 0 to 8123
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   class                     8124 non-null   object
 1   cap-shape                 8124 non-null   object
 2   cap-surface               8124 non-null   object
 3   cap-color                 8124 non-null   object
 4   bruises                   8124 non-null   object
 5   odor                      8124 non-null   object
 6   gill-attachment           8124 non-null   object
 7   gill-spacing              8124 non-null   object
 8   gill-size                 8124 non-null   object
 9   gill-color                8124 non-null   object
 10  stalk-shape               8124 non-null   object
 11  stalk-root                8124 non-null   object
 12  stalk-surface-above-ring  8124 non-null   object
 13  stalk-surface-below-ring  8124 non-null   object
 14  stalk-color-above-ring  

* Gives description

In [6]:
data.describe()

class cap-shape cap-surface cap-color bruises  odor gill-attachment  \
count   8124      8124        8124      8124    8124  8124            8124   
unique     2         6           4        10       2     9               2   
top        e         x           y         n       f     n               f   
freq    4208      3656        3244      2284    4748  3528            7914   

       gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
count          8124      8124       8124  ...                     8124   
unique            2         2         12  ...                        4   
top               c         b          b  ...                        s   
freq           6812      5612       1728  ...                     4936   

       stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
count                    8124                   8124      8124       8124   
unique                      9                      9         1          4   
top                         w                      w         p          w   
freq                     4464                   4384      8124       7924   

       ring-number ring-type spore-print-color population habitat  
count         8124      8124              8124       8124    8124  
unique           3         5                 9          6       7  
top              o         p                 w          v       d  
freq          7488      3968              2388       4040    3148  

[4 rows x 23 columns]

# Define Target(y) and features(x)


In [7]:
data.columns

Index(['class', 'cap-shape', 'cap-surface', 'cap-color', 'bruises', 'odor',
       'gill-attachment', 'gill-spacing', 'gill-size', 'gill-color',
       'stalk-shape', 'stalk-root', 'stalk-surface-above-ring',
       'stalk-surface-below-ring', 'stalk-color-above-ring',
       'stalk-color-below-ring', 'veil-type', 'veil-color', 'ring-number',
       'ring-type', 'spore-print-color', 'population', 'habitat'],
      dtype='object')

In [8]:
y=data['class']
x=data[['cap-shape', 'cap-surface', 'cap-color', 'bruises', 'odor',
       'gill-attachment', 'gill-spacing', 'gill-size', 'gill-color',
       'stalk-shape', 'stalk-root', 'stalk-surface-above-ring',
       'stalk-surface-below-ring', 'stalk-color-above-ring',
       'stalk-color-below-ring', 'veil-type', 'veil-color', 'ring-number',
       'ring-type', 'spore-print-color', 'population', 'habitat']]



In [9]:
x.shape, y.shape

((8124, 22), (8124,))

* co-relation between columns

In [10]:
data.corr

<bound method DataFrame.corr of      class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0        p         x           s         n       t    p               f   
1        e         x           s         y       t    a               f   
2        e         b           s         w       t    l               f   
3        p         x           y         w       t    p               f   
4        e         x           s         g       f    n               f   
...    ...       ...         ...       ...     ...  ...             ...   
8119     e         k           s         n       f    n               a   
8120     e         x           s         n       f    n               a   
8121     e         f           s         n       f    n               a   
8122     p         k           y         n       f    y               f   
8123     e         x           s         n       f    n               a   

     gill-spacing gill-size gill-color  ... stalk-surface-below-rin

### `Use pd.get_dummies() for one hot encoding`

In [11]:
data = pd.get_dummies(data, columns=['cap-shape', 'cap-surface','cap-color','bruises','odor','gill-attachment','gill-color','stalk-surface-below-ring','stalk-color-above-ring','stalk-color-above-ring','veil-type','veil-color','ring-type','spore-print-color','habitat'])

In [12]:
data

class gill-spacing gill-size stalk-shape stalk-root  \
0        p            c         n           e          e   
1        e            c         b           e          c   
2        e            c         b           e          c   
3        p            c         n           e          e   
4        e            w         b           t          e   
...    ...          ...       ...         ...        ...   
8119     e            c         b           e          ?   
8120     e            c         b           e          ?   
8121     e            c         b           e          ?   
8122     p            c         n           t          ?   
8123     e            c         b           e          ?   

     stalk-surface-above-ring stalk-color-below-ring ring-number population  \
0                           s                      w           o          s   
1                           s                      w           o          n   
2                           s                      w           o          n   
3                           s                      w           o          s   
4                           s                      w           o          a   
...                       ...                    ...         ...        ...   
8119                        s                      o           o          c   
8120                        s                      o           o          v   
8121                        s                      o           o          c   
8122                        s                      w           o          v   
8123                        s                      o           o          c   

      cap-shape_b  ...  spore-print-color_u  spore-print-color_w  \
0               0  ...                    0                    0   
1               0  ...                    0                    0   
2               1  ...                    0                    0   
3               0  ...                    0                    0   
4               0  ...                    0                    0   
...           ...  ...                  ...                  ...   
8119            0  ...                    0                    0   
8120            0  ...                    0                    0   
8121            0  ...                    0                    0   
8122            0  ...                    0                    1   
8123            0  ...                    0                    0   

      spore-print-color_y  habitat_d  habitat_g  habitat_l  habitat_m  \
0                       0          0          0          0          0   
1                       0          0          1          0          0   
2                       0          0          0          0          1   
3                       0          0          0          0          0   
4                       0          0          1          0          0   
...                   ...        ...        ...        ...        ...   
8119                    0          0          0          1          0   
8120                    0          0          0          1          0   
8121                    0          0          0          1          0   
8122                    0          0          0          1          0   
8123                    0          0          0          1          0   

      habitat_p  habitat_u  habitat_w  
0             0          1          0  
1             0          0          0  
2             0          0          0  
3             0          1          0  
4             0          0          0  
...         ...        ...        ...  
8119          0          0          0  
8120          0          0          0  
8121          0          0          0  
8122          0          0          0  
8123          0          0          0  

[8124 rows x 102 columns]

* Sklearn labelencoder

In [13]:
from sklearn.preprocessing import LabelEncoder

label_encoder= LabelEncoder()

In [14]:
y= label_encoder.fit_transform(y)
y

array([1, 0, 0, ..., 0, 1, 0])

In [15]:
for i in x:
  x[i] = label_encoder.fit_transform(x [i])

C:\Users\user\AppData\Local\Temp\ipykernel_17180\160269017.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x[i] = label_encoder.fit_transform(x [i])
C:\Users\user\AppData\Local\Temp\ipykernel_17180\160269017.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x[i] = label_encoder.fit_transform(x [i])
C:\Users\user\AppData\Local\Temp\ipykernel_17180\160269017.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value i

# Train, test and split

In [16]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=7474)

In [17]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape 

((5686, 22), (2438, 22), (5686,), (2438,))

* Identify the type of problem and select the model

In [18]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()

* Train the model



In [19]:
model.fit(x_train, y_train)
RandomForestClassifier()

RandomForestClassifier()

* Predict the model

In [20]:
y_pred= model.predict(x_test)

In [21]:
y_pred

array([0, 0, 0, ..., 1, 1, 1])

In [22]:
y_test

array([0, 0, 0, ..., 1, 1, 1])

* Find the accuracy of the model

In [23]:
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

In [24]:
accuracy_score(y_test, y_pred)

1.0

In [25]:
confusion_matrix(y_test,y_pred)

array([[1291,    0],
       [   0, 1147]], dtype=int64)

* classification report

In [26]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1291
           1       1.00      1.00      1.00      1147

    accuracy                           1.00      2438
   macro avg       1.00      1.00      1.00      2438
weighted avg       1.00      1.00      1.00      2438

